var constellations = [
    {
        "name": "Heart",
        "telescope": false,
        "circle": 1,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 1,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Sun",
        "telescope": false,
        "circle": 1,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 1,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": "Daytime"
    },
    {
        "name": "Yavash",
        "telescope": false,
        "circle": 1,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": "Varies"
    },
    {
        "name": "Xibar",
        "telescope": false,
        "circle": 1,
        "magic": 0,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": "Varies"
    },
    {
        "name": "Katamba",
        "telescope": false,
        "circle": 1,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": "Varies"
    },
    {
        "name": "Wolf",
        "telescope": false,
        "circle": 2,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Lion",
        "telescope": false,
        "circle": 3,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 1,
        "dayRise": 251,
        "daySet": 370,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Raven",
        "telescope": false,
        "circle": 4,
        "magic": 0,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Unicorn",
        "telescope": false,
        "circle": 5,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 1,
        "dayRise": 1,
        "daySet": 111,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Boar",
        "telescope": false,
        "circle": 6,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 1,
        "dayRise": 166,
        "daySet": 276,
        "spring": false,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Panther",
        "telescope": false,
        "circle": 7,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 1,
        "dayRise": 287,
        "daySet": 397,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Cobra",
        "telescope": false,
        "circle": 8,
        "magic": 1,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 51,
        "daySet": 161,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Ox",
        "telescope": false,
        "circle": 9,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 1,
        "dayRise": 228,
        "daySet": 338,
        "spring": false,
        "summer": true,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Scorpion",
        "telescope": true,
        "circle": 10,
        "magic": 0,
        "lore": 0,
        "offense": 2,
        "defense": 1,
        "survival": 0,
        "dayRise": 389,
        "daySet": 99,
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Wren",
        "telescope": true,
        "circle": 11,
        "magic": 2,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 72,
        "daySet": 182,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Cat",
        "telescope": false,
        "circle": 12,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Ram",
        "telescope": false,
        "circle": 13,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 2,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "timeRise": 1800,
        "timeSet": 200,
        "note": ""
    },
    {
        "name": "Dolphin",
        "telescope": false,
        "circle": 14,
        "magic": 0,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 1,
        "dayRise": 12,
        "daySet": 123,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Shardstar",
        "telescope": true,
        "circle": 15,
        "magic": 0,
        "lore": 2,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 192,
        "daySet": 306,
        "spring": false,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Nightingale",
        "telescope": false,
        "circle": 15,
        "magic": 2,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 343,
        "daySet": 53,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": true,
        "timeRise": 2200,
        "timeSet": 200,
        "note": ""
    },
    {
        "name": "Wolverine",
        "telescope": false,
        "circle": 16,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 1,
        "dayRise": 38,
        "daySet": 148,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Centaur",
        "telescope": true,
        "circle": 17,
        "magic": 0,
        "lore": 0,
        "offense": 2,
        "defense": 1,
        "survival": 0,
        "dayRise": 234,
        "daySet": 344,
        "spring": false,
        "summer": true,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Magpie",
        "telescope": false,
        "circle": 18,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Weasel",
        "telescope": false,
        "circle": 19,
        "magic": 0,
        "lore": 2,
        "offense": 1,
        "defense": 0,
        "survival": 0,
        "dayRise": 318,
        "daySet": 28,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": true,
        "timeRise": 200,
        "timeSet": 600,
        "note": ""
    },
    {
        "name": "King Snake",
        "telescope": true,
        "circle": 20,
        "magic": 0,
        "lore": 2,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 214,
        "daySet": 324,
        "spring": false,
        "summer": true,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Viper",
        "telescope": true,
        "circle": 21,
        "magic": 0,
        "lore": 0,
        "offense": 2,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "timeRise": 2200,
        "timeSet": 600,
        "note": ""
    },
    {
        "name": "Albatross",
        "telescope": false,
        "circle": 22,
        "magic": 0,
        "lore": 1,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 25,
        "daySet": 135,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Shark",
        "telescope": false,
        "circle": 23,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 1,
        "dayRise": 355,
        "daySet": 65,
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Donkey",
        "telescope": false,
        "circle": 24,
        "magic": 1,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 265,
        "daySet": 375,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Coyote",
        "telescope": false,
        "circle": 25,
        "magic": 1,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 0,
        "dayRise": 377,
        "daySet": 87,
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Dove",
        "telescope": false,
        "circle": 26,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 45,
        "daySet": 195,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Phoenix",
        "telescope": true,
        "circle": 27,
        "magic": 1,
        "lore": 2,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "timeRise": 100,
        "timeSet": 400,
        "note": ""
    },
    {
        "name": "Heron",
        "telescope": false,
        "circle": 28,
        "magic": 0,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 2,
        "dayRise": 131,
        "daySet": 241,
        "spring": true,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Mongoose",
        "telescope": false,
        "circle": 29,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 1,
        "survival": 0,
        "dayRise": 59,
        "daySet": 166,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Goshawk",
        "telescope": false,
        "circle": 30,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 1,
        "dayRise": 361,
        "daySet": 71,
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Owl",
        "telescope": true,
        "circle": 31,
        "magic": 2,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 0,
        "dayRise": 201,
        "daySet": 318,
        "spring": false,
        "summer": true,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Welkin",
        "telescope": false,
        "circle": 32,
        "magic": 0,
        "lore": 1,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 328,
        "daySet": 38,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Raccoon",
        "telescope": false,
        "circle": 33,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 1,
        "dayRise": 111,
        "daySet": 221,
        "spring": true,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Cow",
        "telescope": false,
        "circle": 34,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 2,
        "dayRise": 181,
        "daySet": 291,
        "spring": false,
        "summer": true,
        "fall": false,
        "winter": false,
        "timeRise": 200,
        "timeSet": 400,
        "note": ""
    },
    {
        "name": "Adder",
        "telescope": true,
        "circle": 35,
        "magic": 2,
        "lore": 0,
        "offense": 2,
        "defense": 0,
        "survival": 0,
        "dayRise": 116,
        "daySet": 226,
        "spring": true,
        "summer": true,
        "fall": false,
        "winter": false,
        "timeRise": 2200,
        "timeSet": 400,
        "note": ""
    },
    {
        "name": "Vulture",
        "telescope": true,
        "circle": 36,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 2,
        "survival": 2,
        "dayRise": 274,
        "daySet": 384,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": false,
        "timeRise": 2400,
        "timeSet": 400,
        "note": ""
    },
    {
        "name": "Shrew",
        "telescope": true,
        "circle": 37,
        "magic": 2,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 0,
        "dayRise": 101,
        "daySet": 211,
        "spring": true,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Shrike",
        "telescope": false,
        "circle": 38,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 2,
        "dayRise": 302,
        "daySet": 12,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": true,
        "timeRise": 2400,
        "timeSet": 200,
        "note": ""
    },
    {
        "name": "Jackal",
        "telescope": false,
        "circle": 39,
        "magic": 1,
        "lore": 0,
        "offense": 0,
        "defense": 2,
        "survival": 0,
        "dayRise": 154,
        "daySet": 264,
        "spring": false,
        "summer": true,
        "fall": false,
        "winter": false,
        "timeRise": 2200,
        "timeSet": 200,
        "note": ""
    },
    {
        "name": "Spider",
        "telescope": false,
        "circle": 40,
        "magic": 0,
        "lore": 0,
        "offense": 2,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Giant",
        "telescope": false,
        "circle": 41,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 2,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Hare",
        "telescope": false,
        "circle": 42,
        "magic": 0,
        "lore": 2,
        "offense": 0,
        "defense": 1,
        "survival": 0,
        "dayRise": 153,
        "daySet": 263,
        "spring": false,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Toad",
        "telescope": false,
        "circle": 44,
        "magic": 2,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": 1,
        "daySet": 400,
        "spring": true,
        "summer": true,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "Archer",
        "telescope": true,
        "circle": 45,
        "magic": 0,
        "lore": 0,
        "offense": 2,
        "defense": 0,
        "survival": 2,
        "dayRise": 80,
        "daySet": 185,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Brigantine",
        "telescope": false,
        "circle": 47,
        "magic": 0,
        "lore": 2,
        "offense": 0,
        "defense": 0,
        "survival": 1,
        "dayRise": 360,
        "daySet": 78,
        "spring": true,
        "summer": false,
        "fall": false,
        "winter": true,
        "note": ""
    },
    {
        "name": "Scales",
        "telescope": false,
        "circle": 48,
        "magic": 0,
        "lore": 2,
        "offense": 1,
        "defense": 0,
        "survival": 0,
        "dayRise": 231,
        "daySet": 339,
        "spring": false,
        "summer": true,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "Triquetra",
        "telescope": false,
        "circle": 50,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 0,
        "survival": 1,
        "dayRise": 165,
        "daySet": 276,
        "spring": false,
        "summer": true,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Estrilda",
        "telescope": false,
        "circle": 46,
        "magic": 0,
        "lore": 0,
        "offense": 3,
        "defense": 0,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Verena",
        "telescope": false,
        "circle": 43,
        "magic": 0,
        "lore": 3,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Durgaulda",
        "telescope": false,
        "circle": 49,
        "magic": 3,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Yoakena",
        "telescope": false,
        "circle": 52,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 3,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Penhetia",
        "telescope": false,
        "circle": 55,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 3,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Szeldia",
        "telescope": false,
        "circle": 60,
        "magic": 0,
        "lore": 0,
        "offense": 3,
        "defense": 0,
        "survival": 1,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Merewalda",
        "telescope": true,
        "circle": 65,
        "magic": 0,
        "lore": 0,
        "offense": 1,
        "defense": 3,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Ismenia",
        "telescope": true,
        "circle": 70,
        "magic": 3,
        "lore": 1,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Morleena",
        "telescope": true,
        "circle": 75,
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 1,
        "survival": 3,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Amlothi",
        "telescope": true,
        "circle": 80,
        "magic": 1,
        "lore": 3,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Dawgolesh",
        "telescope": false,
        "circle": 85,
        "magic": 2,
        "lore": 0,
        "offense": 0,
        "defense": 3,
        "survival": 0,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "Er'qutra",
        "telescope": true,
        "circle": 90,
        "magic": 0,
        "lore": 0,
        "offense": 3,
        "defense": 0,
        "survival": 2,
        "dayRise": "--",
        "daySet": "--",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": ""
    },
    {
        "name": "enigma of Kertigen's Forge",
        "telescope": true,
        "circle": 100,
        "magic": 0,
        "lore": 3,
        "offense": 2,
        "defense": 1,
        "survival": 0,
        "dayRise": "166-170",
        "daySet": "278-284",
        "spring": false,
        "summer": true,
        "fall": true,
        "winter": false,
        "note": ""
    },
    {
        "name": "enigma of Dergati's Eye",
        "telescope": true,
        "circle": 125,
        "magic": 2,
        "lore": 1,
        "offense": 1,
        "defense": 1,
        "survival": 1,
        "dayRise": "279-285",
        "daySet": 393,
        "spring": false,
        "summer": false,
        "fall": true,
        "winter": true,
        "note": ""
    },
    {
        "name": "enigma of the Fourth Wall",
        "telescope": "?",
        "circle": "???",
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "",
        "daySet": "",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": "Real-life Seasonal (April Fool's)"
    },
    {
        "name": "Chris' Mass",
        "telescope": "?",
        "circle": "???",
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "",
        "daySet": "",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": "Real-life Seasonal (Christmas)"
    },
    {
        "name": "The Dependents",
        "telescope": "?",
        "circle": "???",
        "magic": 0,
        "lore": 0,
        "offense": 0,
        "defense": 0,
        "survival": 0,
        "dayRise": "",
        "daySet": "",
        "spring": false,
        "summer": false,
        "fall": false,
        "winter": false,
        "note": "Real-life Seasonal (Fourth of July)"
    }
];

function getConstellationNamesBySkillet(skillset) {
    return constellations.reduce(function (item, acc) {
        if (item[skillset] > 0) {
            acc.push(item.name);
        }
        return acc;
    }, []);
};
